### ISSUE TITLE
Transfer to FasterByBike org?

### ISSUE THREAD

**Issue by cmcaine** [cyipt/FasterByBike#2]
Set up a github team for the project as suggested :)

https://github.com/FasterByBike

**Comment by cmcaine** [comment]
Unless you'd prefer a team within the cyipt group? (Also OK)

**Comment by Robinlovelace** [comment]
Job done : )

**Comment by Robinlovelace** [comment]
But I cannot seem to close the issue! Will need to set-up permissions.

**Comment by cmcaine** [comment]
Made you an owner and changed membership privs so that all members will have write permissions to repo. Assuming that means they also get issue closing powers, but IDK.
